# Generated by Django 5.1.1 on 2024-10-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
