# Generated by Django 5.1.1 on 2024-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_profile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pet_adoption/images/'),
        ),
    ]
